### PR TITLE
Change node localstorage emulation to in-memory and remove pkg dependency

### PR DESCRIPTION
**Pull request by steinerj**
## PR Checklist

- [x] Read our contributing guidelines: https://github.com/progress/JSDO/blob/master/contributing.md#contribute-to-the-code-base.

This addresses issue https://github.com/progress/JSDO/issues/182 by swapping out the localstorage emulation dependency for node. This is to enable environments where we can't create swap files, e.g. Kinvey Flex.

### CODE REVIEW

**Comment by joshualan** [comment]
Though this emulation does work (and passes most of our tests), it will break the refresh functionality that we currently support.

**Comment by steinerj** [comment]
@joshualan Thank you for having a look at the PR!
I'm a bit surprised the refresh functionality broke, since it includes an environment switch. The localstorage emulation is only used under _if (isNodeJS) {_

Could you tell me specifics? I'm happy to modify my PR.

**Comment by joshualan** [comment]
@steinerj Actually, I think I'm in the wrong here, I spent some time testing it  and it actually doesn't break refresh in the case I believed it would. I'll merge it in tomorrow.

**Review by joshualan — APPROVED** [review]

**Comment by edselg** [comment]
Internal issue # ADAS-8780.

**Comment by edselg** [comment]
@steinerj 

Hello Julian,

This PR is being closed without merging.

As you are already aware, the core changes in this PR, a LocalStorageEmulation to use in Node.js, was checked-in as part of pull request https://github.com/progress/JSDO/pull/230.

We are also going to use the LocalStorageEmulation with NativeScript in a future version.

Many thank you for your contribution,
Edsel

**Pull request closed without merging**
